import { config } from 'dotenv';
config({
  path: `.env.${process.env.NODE_ENV || 'development'}.local`,
});

export const CREDENTIALS = process.env.CREDENTIALS === 'true';

export const {
  NODE_ENV,
  PORT,
  DB_USERNAME,
  DB_PASSWORD,
  DB_DATABASE,
  SECRET_KEY,
  LOG_FORMAT,
  LOG_DIR,
  ORIGIN,
  EXCHANGE_BASE_URL,
  ACCESS_TOKEN_PRIVATE_KEY,
  REFRESH_TOKEN_PRIVATE_KEY,
  CLIENT_URL,
  COMPANY_LOGO,
  COMPANY_NAME,
  COMPANY_ADDRESS,
  COMPANY_PHONE,
  COMPANY_EMAIL,
  COMPANY_WEBSITE,
  COMPANY_FACEBOOK,
  COMPANY_TWITTER,
  COMPANY_INSTAGRAM,
  COMPANY_YOUTUBE,
  COMPANY_LINKEDIN,
  COMPANY_GITHUB,
  COMPANY_GOOGLE_PLAY,
  COMPANY_APP_STORE,
  EMAIL_SERVICE,
  SENDER_MAIL,
  SENDER_PASSSWORD,
  STRIPE_PRIVATE_KEY,
} = process.env;
